### ISSUE TITLE
compiling melisma2003/key results in 2 errors

### ISSUE THREAD

**Issue by yipcma** [AndreaCogliati/CompleteTranscription#3]
main.c:32:4: error: non-void function 'read_parameter_file' should return a
      value [-Wreturn-type]
          return;
          ^
main.c:40:32: error: non-void function 'read_parameter_file' should return a
      value [-Wreturn-type]

**Comment by yipcma** [comment]
resolved by removing empty returns

**Comment by AndreaCogliati** [comment]
Just change the `return` statements to `return 0` as follows:

	  if(file_specified) {
	      param_stream = fopen(filename, "r");
	      if (param_stream == NULL) {
		  printf("Warning: cannot open \"%s\".  Using defaults.\n", filename);
		  return 0;
	      }
	  }
	  else {
	      filename = "parameters";
	      param_stream = fopen(filename, "r");
	      if(param_stream == NULL) filename = "key/parameters";
	      param_stream = fopen(filename, "r");
	      if(param_stream == NULL) return 0;
	  }

**Comment by AndreaCogliati** [comment]
If you want, contact Dr. David Temperley directly at his website http://davidtemperley.com
